services:
  main:
    platform: linux/amd64
    image: public.ecr.aws/r9r0c2u2/eesimbench/s9-2-two-stage-cmos-op-amp-agent@sha256:1eaad79ca16052e8a8ceff2875327f2c30c9a06293f904a65e7bcd154655c9e5
    pull_policy: always
    command: ["sleep", "infinity"]
    cap_drop: [ALL]
    cap_add: [CHOWN, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    security_opt: ["no-new-privileges:true"]
