from __future__ import annotations


BLOCK_PORTS = {
    "bias_reference": ["vdd1", "0", "vbiasn", "vbiasp"],
    "gain_dac": ["b0", "b1", "b2", "vout", "vdd1", "0"],
    "power_detector": ["rfin", "env", "vdd1", "0"],
    "control_logic": ["enable", "limit", "drive", "vdd1", "0"],
    "pfd": ["refclk", "fbclk", "ext_reset", "up", "dn", "vdd1", "0"],
    "charge_pump": ["up", "dn", "vctrl", "vdd1", "0"],
    "pll_loop_filter": ["cp", "vctrl", "0"],
    "divider_chain_64": ["clkin", "reset", "q2", "q4", "q8", "q16", "q32", "q64", "vdd1", "0"],
    "tx_if_saw1_equiv": ["in", "out", "0"],
    "tx_if_saw2_equiv": ["in", "out", "0"],
    "rx_if1_bpf": ["in", "out", "0"],
    "rx_if2_bpf": ["in", "out", "0"],
    "tx_rf_bpf": ["in", "out", "0"],
    "rx_rf_bpf": ["in", "out", "0"],
    "rf_duplexer": ["antenna", "txport", "rxport", "0"],
    "tx_input_vga": ["inp", "inm", "outp", "outm", "gain", "vdd1", "0"],
    "tx_475m_vga": ["inp", "inm", "outp", "outm", "gain", "vdd1", "0"],
    "rx_if1_vga": ["inp", "inm", "outp", "outm", "gain", "vdd1", "0"],
    "rx_if2_vga": ["inp", "inm", "outp", "outm", "gain", "vdd1", "0"],
    "rx_lna": ["rfin", "rfout", "vdd1", "0", "vbiasg", "vbiasc"],
    "tx_driver": ["rfin", "rfout", "vdd1", "0", "vbiasg"],
    "tx_pa": ["rfin", "rfout", "vdd1", "vdd5", "0", "vbiasdrv", "vbiaspa", "probe_pa_drain", "probe_predriver_drain"],
    "lo_slicer": ["inp", "inm", "clkout", "bias", "vdd1", "0"],
    "lo_buffer_rf": ["inp", "inm", "outp", "outm", "vdd1", "0"],
    "lo_buffer_if": ["inp", "inm", "outp", "outm", "vdd1", "0"],
    "tx_mixer_10m_to_475m": ["inp", "inm", "lop", "lom", "outp", "outm", "tailbias", "vdd1", "0"],
    "tx_mixer_475m_to_rf": ["inp", "inm", "lop", "lom", "outp", "outm", "tailbias", "vdd1", "0"],
    "rx_mixer_rf_to_if1": ["inp", "inm", "lop", "lom", "outp", "outm", "tailbias", "vdd1", "0"],
    "rx_mixer_if1_to_10m": ["inp", "inm", "lop", "lom", "outp", "outm", "tailbias", "vdd1", "0"],
    "vco_465m": ["outp", "outm", "vctrl", "vdd1", "0"],
    "vco_3040m": ["outp", "outm", "vctrl", "vdd1", "0"],
    "vco_2940m": ["outp", "outm", "vctrl", "vdd1", "0"],
    "pll_synth_tx": ["refclk", "div_reset", "pfd_reset", "lop", "lom", "vctrl_out", "probe_feedback", "vdd1", "0"],
    "pll_synth_rx": ["refclk", "div_reset", "pfd_reset", "lop", "lom", "vctrl_out", "probe_feedback", "vdd1", "0"],
    "pll_synth_if": ["refclk", "div_reset", "pfd_reset", "lop", "lom", "vctrl_out", "probe_feedback", "vdd1", "0"],
    "wimax_tx_core": ["bbp", "bbm", "lo465p", "lo465m", "lo3040p", "lo3040m", "rfout", "probe_pa_drain", "vdd1", "vdd5", "0"],
    "wimax_rx_core": ["rfin", "lo2940p", "lo2940m", "lo465p", "lo465m", "outp", "outm", "vdd1", "0"],
    "wimax_transceiver": [
        "bbtxp", "bbtxm", "rxoutp", "rxoutm", "antenna", "ref_tx", "ref_rx", "ref_if",
        "div_reset", "pfd_reset", "vdd1", "vdd5", "0", "probe_tx_lo_p", "probe_tx_lo_m",
        "probe_rx_lo_p", "probe_rx_lo_m", "probe_if_lo_p", "probe_if_lo_m", "probe_tx_feedback",
        "probe_rx_feedback", "probe_if_feedback", "probe_tx_vctrl", "probe_rx_vctrl", "probe_if_vctrl",
        "probe_pa_drain",
    ],
}

REQUIRED_FILES = {name: f"dut/{name}_flat.spice" for name in BLOCK_PORTS}

MINIMUM_COUNTS = {
    "default": {"active": 1},
    "tx_if_saw1_equiv": {"R": 1, "L": 1, "C": 1},
    "tx_if_saw2_equiv": {"R": 1, "L": 1, "C": 1},
    "rx_if1_bpf": {"R": 1, "L": 1, "C": 1},
    "rx_if2_bpf": {"R": 1, "L": 1, "C": 1},
    "tx_rf_bpf": {"R": 1, "L": 1, "C": 1},
    "rx_rf_bpf": {"R": 1, "L": 1, "C": 1},
    "rf_duplexer": {"R": 2, "L": 2, "C": 2},
    "pll_loop_filter": {"R": 1, "C": 1},
    "pfd": {"active": 8},
    "divider_chain_64": {"active": 24},
    "tx_pa": {"active": 8, "L": 2, "C": 2},
    "pll_synth_tx": {"active": 40, "L": 2, "C": 4},
    "pll_synth_rx": {"active": 40, "L": 2, "C": 4},
    "pll_synth_if": {"active": 40, "L": 2, "C": 4},
    "wimax_tx_core": {"active": 40, "R": 10, "L": 8, "C": 12},
    "wimax_rx_core": {"active": 30, "R": 10, "L": 6, "C": 10},
    "wimax_transceiver": {"active": 150, "R": 30, "L": 20, "C": 30},
}
