services:
  main:
    platform: linux/amd64
    image: eesimbench/sample-1-zero-if-rf-soc-mid-agent:local
    build:
      context: ..
      dockerfile: environment/Dockerfile
    command: ["sleep", "infinity"]
    cap_drop: [ALL]
    cap_add: [CHOWN, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    security_opt: ["no-new-privileges:true"]
